ENV: protect against environment being reset
We cannot really recover from this, but at least we'll provide a clearer
error message than trying to call `exec` with an empty string.

diff --git a/Library/ENV/scm/git b/Library/ENV/scm/git
--- a/Library/ENV/scm/git
+++ b/Library/ENV/scm/git
@@ -2,6 +2,11 @@
 # Make sure this shim uses the same Ruby interpreter that is used by Homebrew.
 unset RUBYLIB
 unset RUBYOPT
+if [ -z "$HOMEBREW_RUBY_PATH" ]
+then
+  echo "${0##*/}: The build tool has reset ENV; --env=std required." >&2
+  exit 1
+fi
 exec "$HOMEBREW_RUBY_PATH" -x "$0" "$@"
 #!/usr/bin/env ruby -W0
 
